name: build
description: "Package google cloud function application."

inputs:
    app_name:
        description: "Name of the cloud function application."
        required: true
    version:
        description: "Version of this cloud function application."
        required: true
    environment:
        description: "Environment this application is build for (test/cprod/prod)."
        required: true
    gcp_credentials:
      description: "GCP Service Account JSON credentials with permissions to access and deploy to GKE."
      required: true
    gcp_project_id:
        description: "The GCP project id in which the function is deployed."
        required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: 'set app name'
      id: app_name
      run: |
        GCP_APP_NAME=$(echo "${{ inputs.app_name }}-${{ inputs.version }}" | tr + -)
        APP_ZIP_NAME=${{ inputs.app_name }}-${{ inputs.version }}.zip
        echo $GCP_APP_NAME
        echo $APP_ZIP_NAME
        echo "GCP_APP_NAME=$GCP_APP_NAME" >> $GITHUB_ENV
        echo "APP_ZIP_NAME=$APP_ZIP_NAME" >> $GITHUB_ENV
      shell: bash
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.gcp_credentials }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Set project'
      run: gcloud config set project ${{ inputs.gcp_project_id }}
      shell: bash
    - name: download gcloud functions app
      uses: actions/download-artifact@v4
      with: # NB: downloaded to main directory
        name: gcloud-functions-app
        path: .
    - name: upload source code
      run: |
        gsutil cp ${{ env.APP_ZIP_NAME }} \
          gs://${{ inputs.gcp_project_id }}-cloud-functions-source-code/${{ inputs.environment }}/source/${{ inputs.app_name }}/${{ env.APP_ZIP_NAME }}
      shell: bash
    - name: Deploy
      run: |
        gcloud functions deploy ${{ inputs.app_name }} \
          --source=gs://${{ inputs.gcp_project_id }}-cloud-functions-source-code/${{ inputs.environment }}/source/${{ inputs.app_name }}/${{ env.APP_ZIP_NAME }} \
          --region europe-west4 \
          --gen2
      shell: bash
