name: 'Pipeline (nprod)'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dagster/*'
      - 'cloud_function/*'

permissions:
  contents: read

env:
  GCP_PROJECT_ID: jasper-ginn-dagster

jobs:
  checks:
    name: 'checks'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 'checks'
        uses: ./.github/workflows/templates/checks
        with:
          python_version: "3.11"
          pre_commit_version: "3.1.1"
  build:
    name: 'build'
    runs-on: ubuntu-latest
    needs: checks
    concurrency:
      # This prevents concurrency in building/deploying an environment.
      group: nprod
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up poetry
        uses: snok/install-poetry@v1
      - name: install git-version plugin
        run: |
          poetry self add poetry-git-version-plugin
      - name: 'determine version'
        id: version
        run: |
          VERSION=$(poetry git-version --no-ansi)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: build
        uses: ./.github/workflows/templates/build
        with:
          app_name: dagster-pipes-gcp
          version: ${{ env.VERSION }}
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
  deploy:
    name: 'deploy'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        env:
          VERSION: ${{ needs.build.outputs.VERSION }}
        uses: ./.github/workflows/templates/deploy
        with:
          app_name: dagster-pipes-gcp
          version: ${{ env.VERSION }}
          environment: nprod
          gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          gcp_project_id: ${{ env.GCP_PROJECT_ID }}
